import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  firstName: "",
  lastName: "",
  email: "",
  password: ""
};

const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    // Reducer for user registration
    userRegister: (state, action) => {
      // Update the state with the data from action.payload
      state.firstName = action.payload.firstName;
      state.lastName = action.payload.lastName;
      state.email = action.payload.email;
      state.password = action.payload.password;
    }
  }
});

// Exporting the actions generated by createSlice
export const { userRegister } = userSlice.actions;

// Exporting the reducer to be used in the store
export default userSlice.reducer;